import { Rubik, PT_Mono } from 'next/font/google'
import "./globals.css";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { Metadata } from "next";
import Navbar from '@/components/Navbar';

const sansFont = Rubik({
  subsets: ['latin'],
})

const monoFont = PT_Mono({
  subsets: ['latin'],
  variable: '--font-pt-mono',
  weight: ['400'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${sansFont.className} ${monoFont.variable} dark antialiased`}
      >
        <Toaster />
        <NextTopLoader
          color="var(--primary)"
          height={3}
          showSpinner={false}
        />
        <ClerkProvider appearance={{ theme: shadcn }}>
          <ConvexClientProvider>
            <Navbar />
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
