import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import ConvexClientProvider from '@/components/ConvexClientProvider'
import { Toaster } from 'sonner'
import { shadcn } from '@clerk/themes'
import Navbar from '@/components/Navbar'
import RightSide from '@/components/RightSide'
import NextTopLoader from 'nextjs-toploader';
import Dock from '@/components/Dock'
import ScrollWrapper from '@/components/ScrollWrapper'
import { ScrollArea } from '@radix-ui/react-scroll-area'
import LeftSidebar from '@/components/LeftSidebar'

const sansFont = Rubik({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sansFont.className} antialiased dark`}>
        <Toaster />
        <NextTopLoader
          color="var(--primary)"
          height={3}
          showSpinner={false}
        />
        <ClerkProvider appearance={{ theme: shadcn }}>
          <ConvexClientProvider>
            <main className="flex flex-col justify-center items-center">
              <Navbar />

              <div className="mt-17 w-full flex justify-center items-start h-[calc(100vh-68px)] overflow-y-hidden">
                {/* Left side */}
                <LeftSidebar className="max-md:hidden flex-[1_1_0] min-w-[200px] sticky  self-start" />

                {/* Center */}
                <div className="flex flex-col justify-start items-center grow max-w-2xl w-full overflow-y-scroll scrollbar-none border-r border-l border-foreground/20 min-h-screen">
                  <ScrollArea className='h-screen w-full'>
                    {children}
                  </ScrollArea>
                </div>

                {/* Right side */}
                <RightSide className="max-lg:hidden flex-[1_1_0] min-w-[200px] sticky top-17 self-start" />
                {/* <LeftSidebar className="max-md:hidden flex-[1_1_0] min-w-[200px] sticky  self-start" /> */}

              </div>
            </main>

            <Dock />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}