import type { Metadata } from 'next'
import '../globals.css'
import Navbar from '@/components/Navbar'
import RightSide from '@/components/RightSide'
import Dock from '@/components/Dock'
import { ScrollArea } from '@radix-ui/react-scroll-area'
import LeftSidebar from '@/components/LeftSidebar'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <main className="flex flex-col justify-center items-center">
        <Navbar />

        <div className="mt-17 w-full flex justify-center items-start h-[calc(100vh-68px)] overflow-y-hidden">
          {/* Left side */}
          <LeftSidebar className="max-md:hidden flex-[1_1_0] min-w-[200px] sticky  self-start" />

          {/* Center */}
          <div className="flex flex-col justify-start items-center grow max-w-2xl w-full overflow-y-scroll scrollbar-none border-r border-l border-foreground/20 min-h-screen">
            <ScrollArea className='h-screen w-full'>
              {children}
            </ScrollArea>
          </div>

          {/* Right side */}
          <RightSide className="max-lg:hidden flex-[1_1_0] min-w-[200px] sticky self-start" />
          {/* <LeftSidebar className="max-md:hidden flex-[1_1_0] min-w-[200px] sticky  self-start" /> */}

        </div>
      </main>

      <Dock />
    </>
  )
}